[package]
name = "sns"
version = "0.1.0"
description = "A name service for the Solana Blockchain"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = "1.5.3"
borsh-derive = "1.5.3"
solana-program = "1.18.26"
solana-sdk = "2.1.5"
